export const iconList: any = {
    '.js': 'javascript',
    '.sass': 'sass',
    '.scss': 'sass',
    '.ts': 'typescript',
    '.jsx': 'react',
    '.babel': 'babel',
    '.config': 'config',
    '.css': 'css',
    '.csv': 'csv',
    '.dockerfile': 'docker',
    '.ico': 'favicon',
    '.json': 'json',
    '.html': 'html',
    '.png': 'image',
    '.jpeg': 'image',
    '.jpg': 'image',
    '.svg': 'svg',
    '.less': 'less',
    '.pdf': 'pdf',
    '.doc': 'word',
    '.docx': 'word',
    '.zip': 'zip',
    '.xls': 'xls',
    '.xml': 'xml',
}